// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: lowcode/v1/lowcode.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RowsCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table string             `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Rows  []*structpb.Struct `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *RowsCreateRequest) Reset() {
	*x = RowsCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lowcode_v1_lowcode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RowsCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowsCreateRequest) ProtoMessage() {}

func (x *RowsCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lowcode_v1_lowcode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowsCreateRequest.ProtoReflect.Descriptor instead.
func (*RowsCreateRequest) Descriptor() ([]byte, []int) {
	return file_lowcode_v1_lowcode_proto_rawDescGZIP(), []int{0}
}

func (x *RowsCreateRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *RowsCreateRequest) GetRows() []*structpb.Struct {
	if x != nil {
		return x.Rows
	}
	return nil
}

type RowsCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*structpb.Struct `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *RowsCreateReply) Reset() {
	*x = RowsCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lowcode_v1_lowcode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RowsCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowsCreateReply) ProtoMessage() {}

func (x *RowsCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_lowcode_v1_lowcode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowsCreateReply.ProtoReflect.Descriptor instead.
func (*RowsCreateReply) Descriptor() ([]byte, []int) {
	return file_lowcode_v1_lowcode_proto_rawDescGZIP(), []int{1}
}

func (x *RowsCreateReply) GetRows() []*structpb.Struct {
	if x != nil {
		return x.Rows
	}
	return nil
}

type RowsGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table   string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Columns string `protobuf:"bytes,2,opt,name=columns,proto3" json:"columns,omitempty"`
	Where   string `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
}

func (x *RowsGetRequest) Reset() {
	*x = RowsGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lowcode_v1_lowcode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RowsGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowsGetRequest) ProtoMessage() {}

func (x *RowsGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lowcode_v1_lowcode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowsGetRequest.ProtoReflect.Descriptor instead.
func (*RowsGetRequest) Descriptor() ([]byte, []int) {
	return file_lowcode_v1_lowcode_proto_rawDescGZIP(), []int{2}
}

func (x *RowsGetRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *RowsGetRequest) GetColumns() string {
	if x != nil {
		return x.Columns
	}
	return ""
}

func (x *RowsGetRequest) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

type RowsGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*structpb.Struct `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *RowsGetReply) Reset() {
	*x = RowsGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lowcode_v1_lowcode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RowsGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowsGetReply) ProtoMessage() {}

func (x *RowsGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_lowcode_v1_lowcode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowsGetReply.ProtoReflect.Descriptor instead.
func (*RowsGetReply) Descriptor() ([]byte, []int) {
	return file_lowcode_v1_lowcode_proto_rawDescGZIP(), []int{3}
}

func (x *RowsGetReply) GetRows() []*structpb.Struct {
	if x != nil {
		return x.Rows
	}
	return nil
}

type RowsUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table string             `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Rows  []*structpb.Struct `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *RowsUpdateRequest) Reset() {
	*x = RowsUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lowcode_v1_lowcode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RowsUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowsUpdateRequest) ProtoMessage() {}

func (x *RowsUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lowcode_v1_lowcode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowsUpdateRequest.ProtoReflect.Descriptor instead.
func (*RowsUpdateRequest) Descriptor() ([]byte, []int) {
	return file_lowcode_v1_lowcode_proto_rawDescGZIP(), []int{4}
}

func (x *RowsUpdateRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *RowsUpdateRequest) GetRows() []*structpb.Struct {
	if x != nil {
		return x.Rows
	}
	return nil
}

type RowsUpdateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*structpb.Struct `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *RowsUpdateReply) Reset() {
	*x = RowsUpdateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lowcode_v1_lowcode_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RowsUpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowsUpdateReply) ProtoMessage() {}

func (x *RowsUpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_lowcode_v1_lowcode_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowsUpdateReply.ProtoReflect.Descriptor instead.
func (*RowsUpdateReply) Descriptor() ([]byte, []int) {
	return file_lowcode_v1_lowcode_proto_rawDescGZIP(), []int{5}
}

func (x *RowsUpdateReply) GetRows() []*structpb.Struct {
	if x != nil {
		return x.Rows
	}
	return nil
}

type RowsDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Where string `protobuf:"bytes,2,opt,name=where,proto3" json:"where,omitempty"`
}

func (x *RowsDeleteRequest) Reset() {
	*x = RowsDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lowcode_v1_lowcode_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RowsDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowsDeleteRequest) ProtoMessage() {}

func (x *RowsDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lowcode_v1_lowcode_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowsDeleteRequest.ProtoReflect.Descriptor instead.
func (*RowsDeleteRequest) Descriptor() ([]byte, []int) {
	return file_lowcode_v1_lowcode_proto_rawDescGZIP(), []int{6}
}

func (x *RowsDeleteRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *RowsDeleteRequest) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

type RowsDeleteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RowsDeleteReply) Reset() {
	*x = RowsDeleteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lowcode_v1_lowcode_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RowsDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowsDeleteReply) ProtoMessage() {}

func (x *RowsDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_lowcode_v1_lowcode_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowsDeleteReply.ProtoReflect.Descriptor instead.
func (*RowsDeleteReply) Descriptor() ([]byte, []int) {
	return file_lowcode_v1_lowcode_proto_rawDescGZIP(), []int{7}
}

var File_lowcode_v1_lowcode_proto protoreflect.FileDescriptor

var file_lowcode_v1_lowcode_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x77,
	0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x6f, 0x77, 0x63,
	0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x56, 0x0a, 0x11, 0x52, 0x6f, 0x77, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2b, 0x0a,
	0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x3e, 0x0a, 0x0f, 0x52, 0x6f,
	0x77, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a,
	0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x56, 0x0a, 0x0e, 0x52, 0x6f,
	0x77, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x68, 0x65, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x68, 0x65,
	0x72, 0x65, 0x22, 0x3b, 0x0a, 0x0c, 0x52, 0x6f, 0x77, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22,
	0x56, 0x0a, 0x11, 0x52, 0x6f, 0x77, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x72, 0x6f,
	0x77, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x3e, 0x0a, 0x0f, 0x52, 0x6f, 0x77, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x04, 0x72, 0x6f,
	0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x3f, 0x0a, 0x11, 0x52, 0x6f, 0x77, 0x73, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x68, 0x65, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x77, 0x68, 0x65, 0x72, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x6f, 0x77, 0x73,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x87, 0x03, 0x0a, 0x04,
	0x52, 0x6f, 0x77, 0x73, 0x12, 0x62, 0x0a, 0x0a, 0x52, 0x6f, 0x77, 0x73, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x1d, 0x2e, 0x6c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x6f, 0x77, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x6c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x6f, 0x77, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f, 0x72, 0x6f, 0x77, 0x73, 0x2f, 0x7b, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x7d, 0x3a, 0x01, 0x2a, 0x12, 0x56, 0x0a, 0x07, 0x52, 0x6f, 0x77, 0x73,
	0x47, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x6c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x6f, 0x77, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x6c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x77,
	0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0f, 0x12, 0x0d, 0x2f, 0x72, 0x6f, 0x77, 0x73, 0x2f, 0x7b, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x7d,
	0x12, 0x62, 0x0a, 0x0a, 0x52, 0x6f, 0x77, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1d,
	0x2e, 0x6c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x77, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x6c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x77, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x12, 0x32, 0x0d, 0x2f, 0x72, 0x6f, 0x77, 0x73, 0x2f, 0x7b, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x7d, 0x3a, 0x01, 0x2a, 0x12, 0x5f, 0x0a, 0x0a, 0x52, 0x6f, 0x77, 0x73, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x1d, 0x2e, 0x6c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x6f, 0x77, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x6c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x6f, 0x77, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x2a, 0x0d, 0x2f, 0x72, 0x6f, 0x77, 0x73, 0x2f, 0x7b, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x7d, 0x42, 0x4e, 0x0a, 0x19, 0x64, 0x65, 0x76, 0x2e, 0x6b, 0x72, 0x61,
	0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x2e,
	0x76, 0x31, 0x42, 0x0e, 0x4c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x56, 0x31, 0x50, 0x01, 0x5a, 0x1f, 0x6c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x6d, 0x79,
	0x73, 0x71, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x6f, 0x77, 0x63, 0x6f, 0x64, 0x65, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lowcode_v1_lowcode_proto_rawDescOnce sync.Once
	file_lowcode_v1_lowcode_proto_rawDescData = file_lowcode_v1_lowcode_proto_rawDesc
)

func file_lowcode_v1_lowcode_proto_rawDescGZIP() []byte {
	file_lowcode_v1_lowcode_proto_rawDescOnce.Do(func() {
		file_lowcode_v1_lowcode_proto_rawDescData = protoimpl.X.CompressGZIP(file_lowcode_v1_lowcode_proto_rawDescData)
	})
	return file_lowcode_v1_lowcode_proto_rawDescData
}

var file_lowcode_v1_lowcode_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lowcode_v1_lowcode_proto_goTypes = []interface{}{
	(*RowsCreateRequest)(nil), // 0: lowcode.v1.RowsCreateRequest
	(*RowsCreateReply)(nil),   // 1: lowcode.v1.RowsCreateReply
	(*RowsGetRequest)(nil),    // 2: lowcode.v1.RowsGetRequest
	(*RowsGetReply)(nil),      // 3: lowcode.v1.RowsGetReply
	(*RowsUpdateRequest)(nil), // 4: lowcode.v1.RowsUpdateRequest
	(*RowsUpdateReply)(nil),   // 5: lowcode.v1.RowsUpdateReply
	(*RowsDeleteRequest)(nil), // 6: lowcode.v1.RowsDeleteRequest
	(*RowsDeleteReply)(nil),   // 7: lowcode.v1.RowsDeleteReply
	(*structpb.Struct)(nil),   // 8: google.protobuf.Struct
}
var file_lowcode_v1_lowcode_proto_depIdxs = []int32{
	8, // 0: lowcode.v1.RowsCreateRequest.rows:type_name -> google.protobuf.Struct
	8, // 1: lowcode.v1.RowsCreateReply.rows:type_name -> google.protobuf.Struct
	8, // 2: lowcode.v1.RowsGetReply.rows:type_name -> google.protobuf.Struct
	8, // 3: lowcode.v1.RowsUpdateRequest.rows:type_name -> google.protobuf.Struct
	8, // 4: lowcode.v1.RowsUpdateReply.rows:type_name -> google.protobuf.Struct
	0, // 5: lowcode.v1.Rows.RowsCreate:input_type -> lowcode.v1.RowsCreateRequest
	2, // 6: lowcode.v1.Rows.RowsGet:input_type -> lowcode.v1.RowsGetRequest
	4, // 7: lowcode.v1.Rows.RowsUpdate:input_type -> lowcode.v1.RowsUpdateRequest
	6, // 8: lowcode.v1.Rows.RowsDelete:input_type -> lowcode.v1.RowsDeleteRequest
	1, // 9: lowcode.v1.Rows.RowsCreate:output_type -> lowcode.v1.RowsCreateReply
	3, // 10: lowcode.v1.Rows.RowsGet:output_type -> lowcode.v1.RowsGetReply
	5, // 11: lowcode.v1.Rows.RowsUpdate:output_type -> lowcode.v1.RowsUpdateReply
	7, // 12: lowcode.v1.Rows.RowsDelete:output_type -> lowcode.v1.RowsDeleteReply
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_lowcode_v1_lowcode_proto_init() }
func file_lowcode_v1_lowcode_proto_init() {
	if File_lowcode_v1_lowcode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lowcode_v1_lowcode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RowsCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lowcode_v1_lowcode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RowsCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lowcode_v1_lowcode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RowsGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lowcode_v1_lowcode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RowsGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lowcode_v1_lowcode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RowsUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lowcode_v1_lowcode_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RowsUpdateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lowcode_v1_lowcode_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RowsDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lowcode_v1_lowcode_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RowsDeleteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lowcode_v1_lowcode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lowcode_v1_lowcode_proto_goTypes,
		DependencyIndexes: file_lowcode_v1_lowcode_proto_depIdxs,
		MessageInfos:      file_lowcode_v1_lowcode_proto_msgTypes,
	}.Build()
	File_lowcode_v1_lowcode_proto = out.File
	file_lowcode_v1_lowcode_proto_rawDesc = nil
	file_lowcode_v1_lowcode_proto_goTypes = nil
	file_lowcode_v1_lowcode_proto_depIdxs = nil
}
